# Generated by Django 5.2 on 2025-09-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_og_guest',
            new_name='no_of_guest',
        ),
    ]
