# Generated by Django 5.2 on 2025-09-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_no_og_guest_booking_no_of_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=1, max_digits=1)),
                ('inventory', models.IntegerField(default=1)),
            ],
        ),
    ]
