# Generated by Django 5.2 on 2025-09-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_ali'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ali',
        ),
    ]
